"""Callback, stop, and channel-forward handling for the Telegram chat connector.

Handles inline approval buttons, MessageGenerationStopped events, and the channel-post mapping
recorded from automatic forwards into the linked discussion group.
"""

import contextlib
import html
import inspect
import logging
import re
from collections.abc import Awaitable, Callable
from typing import Any

from lyoko.domain.models.chat import ApprovalResponse
from lyoko.infrastructure.chat.streamer import TelegramStreamingReply
from telegram import Update
from telegram.ext import ContextTypes

logger = logging.getLogger("lyoko.chat.telegram")


def _strip_tags(text: str) -> str:
    """Remove Telegram HTML tags, used when re-editing a message that was sent as plain text."""
    return re.sub(r"<[^>]+>", "", text)


class TelegramCallbackMixin:
    """Handle button clicks and channel-forward mapping."""

    _active_streamers: dict[tuple[str, int], TelegramStreamingReply]
    _channel_to_discussion: dict[tuple[str, int], int]
    _approval_handlers: list[Callable[[ApprovalResponse], Awaitable[None]]]
    _approval_message_html: dict[tuple[str, int], tuple[str, str | None]]

    async def _handle_stop_callback(self, query: Any, chat_id: str | None, message_id: str) -> None:
        """Stop the in-flight generation whose streaming placeholder carries the stop button."""
        try:
            key = (str(chat_id), int(message_id))
        except (TypeError, ValueError):
            return
        streamer = self._active_streamers.get(key)
        if streamer is not None:
            logger.info(
                "User requested stop for streaming reply %s in chat %s", message_id, chat_id
            )
            streamer.stop()
        with contextlib.suppress(Exception):
            await query.edit_message_reply_markup(reply_markup=None)

    async def _handle_callback_query(
        self, update: Update, context: ContextTypes.DEFAULT_TYPE
    ) -> None:
        """Handle callback queries generated by inline keyboard buttons."""
        query = update.callback_query
        if not query or not query.data or not update.effective_user:
            return

        user_id = str(update.effective_user.id)
        chat_id = str(update.effective_chat.id) if update.effective_chat else None

        # Button clicks require user authorization (or authorized channel)
        if not self.is_user_authorized(user_id) and not self.is_chat_authorized(chat_id):
            await query.answer("⛔ Unauthorized", show_alert=True)
            return

        await query.answer()

        # Format: "<action_id>:<payload>" e.g. "approve:<incident_id>" or "stop:<message_id>"
        parts = query.data.split(":", 1)
        action_type = parts[0]
        payload = parts[1] if len(parts) > 1 else ""

        if action_type.lower() == "stop":
            await self._handle_stop_callback(query, chat_id, payload)
            return

        incident_id = payload
        approved = action_type.lower() == "approve"
        is_force = action_type.lower() == "force"
        is_feedback = action_type.lower() in ["feedback", "teach", "redirect"]

        reason = (
            "User confirmed via Telegram button"
            if approved
            else (
                "User forced investigation via Telegram button"
                if is_force
                else (
                    "User requested redirection / teaching new rule"
                    if is_feedback
                    else "User rejected via Telegram button"
                )
            )
        )

        response = ApprovalResponse(
            incident_id=incident_id,
            approved=approved or is_force,
            user_id=user_id,
            action_id=action_type,
            reason=reason,
        )

        for handler in self._approval_handlers:
            try:
                res = handler(response)
                if inspect.isawaitable(res):
                    await res
            except Exception as exc:
                logger.error("Error executing approval handler: %s", exc)

        user_name = html.escape(update.effective_user.first_name or user_id)
        if approved:
            status_text = f"✅ <b>Approved</b> by admin ({user_name})."
        elif is_force:
            status_text = f"🚀 <b>Investigation forced</b> by admin ({user_name})."
        elif is_feedback:
            status_text = (
                f"💡 <b>Redirection / Teaching mode activated</b> by {user_name}.\n\n"
                f"👉 <i>Reply to this message or type:</i>\n"
                f"<code>/feedback &lt;your correction or rule for this service&gt;</code>"
            )
        else:
            status_text = f"❌ <b>Rejected</b> by admin ({user_name})."

        # Telegram strips an answered message's formatting from `text`, so reuse the markup we
        # originally sent (kept by the connector) to avoid losing every bold label on the edit.
        message_id = getattr(query.message, "message_id", None) if query.message else None
        stored = None
        if chat_id is not None and message_id is not None:
            stored = self._approval_message_html.pop((str(chat_id), int(message_id)), None)
        if stored is not None:
            current_text, parse_mode = stored
        else:
            current_text, parse_mode = (query.message.text or "" if query.message else ""), "HTML"

        if parse_mode is None:
            current_text = _strip_tags(current_text)
            result_text = _strip_tags(status_text)
        else:
            result_text = f"<b>Result:</b> {status_text}"
        new_text = f"{current_text}\n\n{result_text}" if current_text else result_text
        try:
            await query.edit_message_text(new_text, parse_mode=parse_mode)
        except Exception as edit_err:
            logger.debug("Could not edit message text after callback: %s", edit_err)

    def _record_channel_forward(self, msg: Any) -> None:
        """Record a channel-post -> discussion-message mapping from an automatic forward."""
        channel_id = None
        channel_msg_id = None

        origin = getattr(msg, "forward_origin", None)
        if origin and getattr(origin, "type", "") == "channel":
            chat_obj = getattr(origin, "chat", None)
            channel_id = str(chat_obj.id) if chat_obj else None
            channel_msg_id = getattr(origin, "message_id", None)
        elif getattr(msg, "is_automatic_forward", False) or getattr(msg, "forward_from_chat", None):
            from_chat = getattr(msg, "forward_from_chat", None)
            if from_chat:
                channel_id = str(from_chat.id)
                channel_msg_id = getattr(msg, "forward_from_message_id", None)

        if channel_id and channel_msg_id is not None:
            key = (str(channel_id), int(channel_msg_id))
            self._channel_to_discussion[key] = msg.message_id
            logger.info(
                "Mapped channel post %s to discussion message %s",
                key,
                msg.message_id,
            )
