"""Callback, stop, and channel-forward handling for the Telegram chat connector.

Handles inline approval buttons, MessageGenerationStopped events, and the channel-post mapping
recorded from automatic forwards into the linked discussion group.
"""

import html
import inspect
import logging
from collections.abc import Awaitable, Callable
from typing import Any

from lyoko.domain.models.chat import ApprovalResponse
from lyoko.infrastructure.chat.streamer import TelegramDraftStreamer
from telegram import Update
from telegram.ext import ContextTypes

logger = logging.getLogger("lyoko.chat.telegram")


class TelegramCallbackMixin:
    """Handle button clicks, streamed-generation stops, and channel-forward mapping."""

    _active_streamers: dict[tuple[str, int], TelegramDraftStreamer]
    _channel_to_discussion: dict[tuple[str, int], int]
    _approval_handlers: list[Callable[[ApprovalResponse], Awaitable[None]]]

    async def _handle_stopped_generation(
        self, update: Update, context: ContextTypes.DEFAULT_TYPE
    ) -> None:
        """Handle MessageGenerationStopped event when user clicks Stop on a streaming draft."""
        stopped = getattr(update, "stopped_message_generation", None)
        if not stopped and hasattr(update, "to_dict"):
            stopped = update.to_dict().get("stopped_message_generation")
        if not stopped:
            return

        chat_data = (
            getattr(stopped, "chat", None)
            if hasattr(stopped, "chat")
            else (stopped.get("chat") if isinstance(stopped, dict) else None)
        )
        chat_id = str(
            getattr(chat_data, "id", "")
            or (chat_data.get("id", "") if isinstance(chat_data, dict) else "")
        )
        draft_id = (
            getattr(stopped, "draft_id", None)
            if hasattr(stopped, "draft_id")
            else (stopped.get("draft_id") if isinstance(stopped, dict) else None)
        )

        if chat_id and draft_id is not None:
            key = (str(chat_id), int(draft_id))
            streamer = self._active_streamers.get(key)
            if streamer is not None:
                logger.info(
                    "User requested stop for streaming draft %s in chat %s", draft_id, chat_id
                )
                streamer.stop()

    async def _handle_callback_query(
        self, update: Update, context: ContextTypes.DEFAULT_TYPE
    ) -> None:
        """Handle callback queries generated by inline keyboard buttons."""
        query = update.callback_query
        if not query or not query.data or not update.effective_user:
            return

        user_id = str(update.effective_user.id)
        chat_id = str(update.effective_chat.id) if update.effective_chat else None

        # Button clicks require user authorization (or authorized channel)
        if not self.is_user_authorized(user_id) and not self.is_chat_authorized(chat_id):
            await query.answer("⛔ Unauthorized", show_alert=True)
            return

        await query.answer()

        # Format: "<action_id>:<incident_id>" e.g. "approve:<incident_id>"
        parts = query.data.split(":", 1)
        action_type = parts[0]
        incident_id = parts[1] if len(parts) > 1 else ""
        approved = action_type.lower() == "approve"
        is_force = action_type.lower() == "force"
        is_feedback = action_type.lower() in ["feedback", "teach", "redirect"]

        reason = (
            "User confirmed via Telegram button"
            if approved
            else (
                "User forced investigation via Telegram button"
                if is_force
                else (
                    "User requested redirection / teaching new rule"
                    if is_feedback
                    else "User rejected via Telegram button"
                )
            )
        )

        response = ApprovalResponse(
            incident_id=incident_id,
            approved=approved or is_force,
            user_id=user_id,
            action_id=action_type,
            reason=reason,
        )

        for handler in self._approval_handlers:
            try:
                res = handler(response)
                if inspect.isawaitable(res):
                    await res
            except Exception as exc:
                logger.error("Error executing approval handler: %s", exc)

        user_name = html.escape(update.effective_user.first_name or user_id)
        if approved:
            status_text = f"✅ <b>Approved</b> by admin ({user_name})."
        elif is_force:
            status_text = f"🚀 <b>Investigation forced</b> by admin ({user_name})."
        elif is_feedback:
            status_text = (
                f"💡 <b>Redirection / Teaching mode activated</b> by {user_name}.\n\n"
                f"👉 <i>Reply to this message or type:</i>\n"
                f"<code>/feedback &lt;your correction or rule for this service&gt;</code>"
            )
        else:
            status_text = f"❌ <b>Rejected</b> by admin ({user_name})."

        current_text = (
            query.message.text
            if query.message and hasattr(query.message, "text") and query.message.text
            else ""
        )
        if current_text:
            new_text = f"{current_text}\n\n<b>Result:</b> {status_text}"
        else:
            new_text = f"<b>Result:</b> {status_text}"
        try:
            await query.edit_message_text(new_text, parse_mode="HTML")
        except Exception as edit_err:
            logger.debug("Could not edit message text after callback: %s", edit_err)

    def _record_channel_forward(self, msg: Any) -> None:
        """Record a channel-post -> discussion-message mapping from an automatic forward."""
        channel_id = None
        channel_msg_id = None

        origin = getattr(msg, "forward_origin", None)
        if origin and getattr(origin, "type", "") == "channel":
            chat_obj = getattr(origin, "chat", None)
            channel_id = str(chat_obj.id) if chat_obj else None
            channel_msg_id = getattr(origin, "message_id", None)
        elif getattr(msg, "is_automatic_forward", False) or getattr(msg, "forward_from_chat", None):
            from_chat = getattr(msg, "forward_from_chat", None)
            if from_chat:
                channel_id = str(from_chat.id)
                channel_msg_id = getattr(msg, "forward_from_message_id", None)

        if channel_id and channel_msg_id is not None:
            key = (str(channel_id), int(channel_msg_id))
            self._channel_to_discussion[key] = msg.message_id
            logger.info(
                "Mapped channel post %s to discussion message %s",
                key,
                msg.message_id,
            )
